//// Weak Script Lexical Analysis Engine
//// Lexical Defination File
//// For c99 / c++11
const int LEX_ID = 1 ;
const int LEX_IF = 2 ;
const int LEX_ELSE = 3 ;
const int LEX_FOR = 4 ;
const int LEX_VAR = 5 ;
const int LEX_RETURN = 6 ;
const int LEX_FUNC = 7 ;
const int LEX_WHILE = 8 ;
const int LEX_BREAK = 9 ;
const int LEX_CONTINUE = 10 ;
const int LEX_SEMI = 11 ;
const int LEX_LSB = 12 ;
const int LEX_RSB = 13 ;
const int LEX_LP = 14 ;
const int LEX_RP = 15 ;
const int LEX_LCB = 16 ;
const int LEX_RCB = 17 ;
const int LEX_COM = 18 ;
const int LEX_POT = 19 ;
const int LEX_COL = 20 ;
const int LEX_ADD = 21 ;
const int LEX_SUB = 22 ;
const int LEX_MUL = 23 ;
const int LEX_DIV = 24 ;
const int LEX_MOD = 25 ;
const int LEX_EQ = 26 ;
const int LEX_ASSIGN = 27 ;
const int LEX_NEQ = 28 ;
const int LEX_GT = 29 ;
const int LEX_NGT = 30 ;
const int LEX_LT = 31 ;
const int LEX_NLT = 32 ;
const int LEX_NUMBER = 33 ;
const int LEX_STRING = 34 ;
const int LEX_SPACE = 35 ;
const int LEX_NL = 36 ;
const int LEX_TAB = 37 ;

